// default package
// Generated Apr 6, 2023, 1:53:34 AM by Hibernate Tools 6.1.7.Final
package com.iti.sakilaapi.domain;

import jakarta.persistence.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category"
        , catalog = "sakila"
)
public class Category implements java.io.Serializable {


    private Byte categoryId;
    private String name;
    private Date lastUpdate;
    private Set filmCategories = new HashSet(0);

    public Category() {
    }


    public Category(String name, Date lastUpdate) {
        this.name = name;
        this.lastUpdate = lastUpdate;
    }

    public Category(String name, Date lastUpdate, Set filmCategories) {
        this.name = name;
        this.lastUpdate = lastUpdate;
        this.filmCategories = filmCategories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "category_id", unique = true, nullable = false)
    public Byte getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Byte categoryId) {
        this.categoryId = categoryId;
    }


    @Column(name = "name", nullable = false, length = 25)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update", nullable = false, length = 19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
    public Set getFilmCategories() {
        return this.filmCategories;
    }

    public void setFilmCategories(Set filmCategories) {
        this.filmCategories = filmCategories;
    }


}


