// default package
// Generated Apr 6, 2023, 1:53:34 AM by Hibernate Tools 6.1.7.Final
package com.iti.sakilaapi.domain;

import jakarta.persistence.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country"
        , catalog = "sakila"
)
public class Country implements java.io.Serializable {


    private Short countryId;
    private String country;
    private Date lastUpdate;
    private Set cities = new HashSet(0);

    public Country() {
    }


    public Country(String country, Date lastUpdate) {
        this.country = country;
        this.lastUpdate = lastUpdate;
    }

    public Country(String country, Date lastUpdate, Set cities) {
        this.country = country;
        this.lastUpdate = lastUpdate;
        this.cities = cities;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "country_id", unique = true, nullable = false)
    public Short getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Short countryId) {
        this.countryId = countryId;
    }


    @Column(name = "country", nullable = false, length = 50)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update", nullable = false, length = 19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set getCities() {
        return this.cities;
    }

    public void setCities(Set cities) {
        this.cities = cities;
    }


}


