// default package
// Generated Apr 6, 2023, 1:53:34 AM by Hibernate Tools 6.1.7.Final

package com.iti.sakilaapi.domain;

import jakarta.persistence.*;

/**
 * SalesByFilmCategory generated by hbm2java
 */
@Entity
@Table(name = "sales_by_film_category"
        , catalog = "sakila"
)
public class SalesByFilmCategory implements java.io.Serializable {


    private SalesByFilmCategoryId id;

    public SalesByFilmCategory() {
    }

    public SalesByFilmCategory(SalesByFilmCategoryId id) {
        this.id = id;
    }

    @EmbeddedId


    @AttributeOverrides({
            @AttributeOverride(name = "category", column = @Column(name = "category", nullable = false, length = 25)),
            @AttributeOverride(name = "totalSales", column = @Column(name = "total_sales", precision = 27, scale = 2))})
    public SalesByFilmCategoryId getId() {
        return this.id;
    }

    public void setId(SalesByFilmCategoryId id) {
        this.id = id;
    }


}


